baseURL = "https://www.marcogomiero.com"
languageCode = "en"                                      
defaultContentLanguage = "en"                           
title = "Marco Gomiero"                                   
theme = "LoveIt"                                         
paginate = 12                                            
enableEmoji = true                                       
enableRobotsTXT = true                                   
googleAnalytics = "UA-90975904-1"                                    
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
publishDir = "docs"                                                         
                                               
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

staticDir = ["static", "../assets/others"]               

[author]                                              
  name = "Marco Gomiero"

[sitemap]                                             
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]                                                
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts"
    weight = 1

  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "talks"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 30

  [[menu.main]]
    name = "About"
    url = "about-me/"
    weight = 40
    
[params]

  dateFormatToUse = "2 Jan 2006"
  dateFormatToUsePost = "2 Jan"

  version = "5.x"                                        
  description = "Software Engineer · Community Manager"                      
  keywords = ["Marco Gomiero", "Android", "Flutter", "Gomiero", "Kotlin", "RSS Parser", "Kotlin Multiplatform"]                  

                                                      
  home_mode = "post"                                     
  home_paginate = 6
  talk_paginate = 10                                      
  avatar = "img/profile.jpeg"                           
  homeTitle = "Marco Gomiero"
  subtitle = "Software Engineer · Community Manager · International Speaker"  

  socialShare = true                                     

  since = 2017                                          
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  linkToMarkdown = false 

  google_verification = "7rDTNqn214SsZ9mmV8Ps5v2vqy8aXFWyoq08udChYCs"

 [params.cdn]                                       
    fontawesome_free_css = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'                           # for example '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'

  [params.social]                                        
    Twitter = "marcoGomier"
    Linkedin = "marco-gomiero-a80857ab"
    GitHub = "prof18"

  [params.share]                                         
    enable = true
    Twitter = true
    Reddit = true
    Linkedin = true

[privacy]                                             
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]                                          
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]                              
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]                                             
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]